### ISSUE TITLE
[3.X] Mesanger Last seen 

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#97]
To me it looks like that the last seen time is wrong it's the same value as the last massage.

**Comment by modulebaan** [comment]
It's the one that's returned by the API. I can't improve that.

**Comment by Nokius** [comment]
what about removing last seen then? 
What is the reason to show last seen which is wrong.

**Comment by modulebaan** [comment]
Well I can remove it if you like, the reason is that Tinder reports the last seen date. I only display it.

**Comment by modulebaan** [comment]
@Nokius 
As you can see here: https://gist.github.com/rtt/10403467#get-updates
is the last_activity_date the same as the last message. This is a privacy thing I think... It worked the same in the V2.X version.

**Comment by Nokius** [comment]
I see, the iOS application is lacking this feature, Yeah but as I understand it it should show the last activity of the user. May my matches don't use tinder often 😉

**Comment by modulebaan** [comment]
Oh, I only have an Android phone available to check the original app. The last time I checked it has the same (buggy) feature, that's why I marked it as normal :p
After some investigation I saw that when you didn't send any message the last activity date is the one when you matched and in all other cases the one from the last message.

**Comment by Nokius** [comment]
Okay then sailfinder has the same behaviour 😄

**Comment by modulebaan** [comment]
I don't care about this 'feature' but I thought maybe someone needs it...
